#!/bin/python

import numpy as np

def trimvalues(values, cutoff):
    sv = sorted(values)
    n = round(len(values) * cutoff)

    var = []
    for i in range(len(values) - n):
        var += [np.std(sv[i:n+i])]

    i = var.index(min(var))
    return sv[i:n+i]
#
#A = [ 0, 10, 11, 10, 11, 20, 18, 9, 8, 10, 18,6,7,8,9,12]
#tA = trimvalues(A, 0.7)
#
#
#print("    mean   stddev")
#print("A:  %.2f  %.2f" % (np.mean(A), np.std(A)))
#print("tA: %.2f   %.2f" % (np.mean(tA), np.std(tA)))
#
#print(tA)
